package taiyari.ObservacionesTratamiento;

import javax.swing.JOptionPane;
import taiyari.Ayudas;
import taiyari.Perfiles.frmPerfilAlumno;
import taiyari.Sesion;
import taiyari.UsuarioDAO;
import taiyari.frmInicioAlumno;

//  @author XiCode, desarolladora por:  Jorge García,   Uriel Gonzalez,     Yhostin Ramirez    y Cristopher Escamilla.

public class frmBitacora extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmBitacora.class.getName());

    //Creación del frame: frmBitacora
    
    public frmBitacora() {
        initComponents();
        Ayudas.maximizarVentana(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        btnAlegre = new javax.swing.JButton();
        btnNormal = new javax.swing.JButton();
        btnDesanimado = new javax.swing.JButton();
        btnTriste = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAnotacion = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnInicioPerfilAlumno = new javax.swing.JButton();
        btnRegistarBitacoraAlumno = new javax.swing.JButton();
        btnSolicitarCitaAlumno = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnInicioAlumno = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnAlegre.setText("Feliz");
        btnAlegre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlegreActionPerformed(evt);
            }
        });

        btnNormal.setText("Normal");
        btnNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNormalActionPerformed(evt);
            }
        });

        btnDesanimado.setText("Desanimado");
        btnDesanimado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesanimadoActionPerformed(evt);
            }
        });

        btnTriste.setText("Triste");
        btnTriste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTristeActionPerformed(evt);
            }
        });

        txtAnotacion.setColumns(20);
        txtAnotacion.setRows(5);
        jScrollPane1.setViewportView(txtAnotacion);

        jPanel1.setBackground(new java.awt.Color(102, 187, 106));

        btnInicioPerfilAlumno.setBackground(new java.awt.Color(102, 187, 106));
        btnInicioPerfilAlumno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInicioPerfilAlumno.setForeground(new java.awt.Color(255, 255, 255));
        btnInicioPerfilAlumno.setText("Perfil");
        btnInicioPerfilAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioPerfilAlumnoActionPerformed(evt);
            }
        });

        btnRegistarBitacoraAlumno.setBackground(new java.awt.Color(102, 187, 106));
        btnRegistarBitacoraAlumno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistarBitacoraAlumno.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistarBitacoraAlumno.setText("Registrar Emoción");
        btnRegistarBitacoraAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarBitacoraAlumnoActionPerformed(evt);
            }
        });

        btnSolicitarCitaAlumno.setBackground(new java.awt.Color(102, 187, 106));
        btnSolicitarCitaAlumno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSolicitarCitaAlumno.setForeground(new java.awt.Color(255, 255, 255));
        btnSolicitarCitaAlumno.setText("Solicitar Cita");
        btnSolicitarCitaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarCitaAlumnoActionPerformed(evt);
            }
        });

        btnCerrarSesion.setBackground(new java.awt.Color(102, 187, 106));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnInicioAlumno.setBackground(new java.awt.Color(102, 187, 106));
        btnInicioAlumno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInicioAlumno.setForeground(new java.awt.Color(255, 255, 255));
        btnInicioAlumno.setText("Inicio");
        btnInicioAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnCerrarSesion)
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRegistarBitacoraAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInicioPerfilAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInicioAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSolicitarCitaAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(btnInicioAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnInicioPerfilAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnRegistarBitacoraAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnSolicitarCitaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(371, 371, 371)
                .addComponent(btnCerrarSesion)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel1.setText("Feliz");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(297, 297, 297)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnNormal)
                        .addGap(58, 58, 58)
                        .addComponent(btnDesanimado)
                        .addGap(64, 64, 64)
                        .addComponent(btnTriste))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAlegre)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNormal)
                    .addComponent(btnDesanimado)
                    .addComponent(btnTriste)
                    .addComponent(btnAlegre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       String emocion ;
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        UsuarioDAO registro = new UsuarioDAO();
        String anotaciones = txtAnotacion.getText();
        String usuario_actual = Sesion.getNombreUsuario();
        
        registro.registrarBitacora(emocion, anotaciones, usuario_actual);
    


        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAlegreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlegreActionPerformed
        emocion = "Alegre";
      
    }//GEN-LAST:event_btnAlegreActionPerformed

    private void btnDesanimadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesanimadoActionPerformed
        // TODO add your handling code here:
        emocion = "Desanimado";
    }//GEN-LAST:event_btnDesanimadoActionPerformed

    private void btnNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormalActionPerformed
        // TODO add your handling code here:
        emocion = "Normal";
    }//GEN-LAST:event_btnNormalActionPerformed

    private void btnTristeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTristeActionPerformed
        // TODO add your handling code here:
        emocion = "Triste";
    }//GEN-LAST:event_btnTristeActionPerformed

    private void btnInicioPerfilAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioPerfilAlumnoActionPerformed
        new frmPerfilAlumno().setVisible(true);     this.dispose();
    }//GEN-LAST:event_btnInicioPerfilAlumnoActionPerformed

    private void btnRegistarBitacoraAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarBitacoraAlumnoActionPerformed
        JOptionPane.showMessageDialog(null, "Actualmente se encuentra navegando en esta pantalla.");
    }//GEN-LAST:event_btnRegistarBitacoraAlumnoActionPerformed

    private void btnSolicitarCitaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarCitaAlumnoActionPerformed
        new frmCitaAlumno().setVisible(true); this.dispose();
    }//GEN-LAST:event_btnSolicitarCitaAlumnoActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        new Ayudas().volverAInicioSesion(frmBitacora.this);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnInicioAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioAlumnoActionPerformed
        new frmInicioAlumno().setVisible(true);	this.dispose();
    }//GEN-LAST:event_btnInicioAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmBitacora().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlegre;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnDesanimado;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInicioAlumno;
    private javax.swing.JButton btnInicioPerfilAlumno;
    private javax.swing.JButton btnNormal;
    private javax.swing.JButton btnRegistarBitacoraAlumno;
    private javax.swing.JButton btnSolicitarCitaAlumno;
    private javax.swing.JButton btnTriste;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAnotacion;
    // End of variables declaration//GEN-END:variables
}
